### ISSUE TITLE
Possibility of a FireFox-version?

### ISSUE THREAD

**Issue by Qqwy** [hay/rare-tijden#2]
What a nifty idea!

It would be great if this extension would also work under FireFox. Do you happen to know how much work this would be?

**Comment by hay** [comment]
Hey, sorry for just noticing your issue. As far as i know the current Firefox extension system is pretty similar to Chrome, and this extension is *really* small (under a 100 lines) so i suppose porting wouldn't be much of an issue. If you want to port the code, feel free to do so!

**Comment by hay** [comment]
I just tested this out, and it seems the extension is completely compatible with Firefox without me having done anything, so that's great. It should be available in a couple of days from this url: https://addons.mozilla.org/en-US/firefox/addon/rare-tijden/
