### ISSUE TITLE
Belgische website support + aanpassing tekst

### ISSUE THREAD

**Issue by said50** [hay/rare-tijden#3]
Zou leuk zijn als het ook op Belgische sites werkt zoals:
standaard.be
demorgen.be
tijd.be
hln.be
vrt.be/vrtnws/
nieuwsblad.be

Zou ook handig zijn als je de tekst kan aanpassen, in België spreekt men vooral van "het zijn vreemde tijden"

**Comment by hay** [comment]
Goed idee! Ik heb het aangepast in de meest recente versie en zou met een auto-update ook in jouw browser moeten komen. Ik heb de sites die je hier noemt meegenomen en het zinnetje. Maak vooral een nieuwe issue aan als je nog meer nieuwssites hebt.
